language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  matrix:
  - PACKAGE="decompress" OCAML_VERSION=4.08 TESTS=true
  - PACKAGE="decompress" OCAML_VERSION=4.09 TESTS=true
  - PACKAGE="decompress" OCAML_VERSION=4.10 TESTS=true
  - PACKAGE="decompress" OCAML_VERSION=4.11 TESTS=true
